cmake: Fix linker warning LNK4291 when linking static lib to the final binary
ngtcp2/nghttp3 pull request #237
Opened 2024-07-15 14:07 UTC by mludha

Apparently some functions (e.g. nghttp3_balloc_clear) create xdata sections in the lib. These are used on 64bit platforms to judge which control flow transitions should be allowed. Normally they are needed only in uncommon cases like longjmp, SEH exceptions or SetThreadContext Windows API calls. These functions don't do anything to warrant it. This flag should just let the compiler do it's thing more efficiently.

2024-07-17 10:19 UTC, tatsuhiro-t commented
It looks like these flags should be for x86_64 only.

2024-07-17 13:35 UTC, mludha commented
They are necessary for x86_64 and silently ignored elsewhere. Shall I add them only for that platform?

2024-07-17 13:46 UTC, tatsuhiro-t commented
See this error message: https://github.com/ngtcp2/nghttp3/actions/runs/9940936525/job/27555228972?pr=237

> LINK : fatal error LNK1246: '/GUARD:EHCONT' not compatible with 'x86' target machine; link without '/GUARD:EHCONT'

2024-07-22 07:54 UTC, tatsuhiro-t requested changes

2024-07-22 07:54 UTC, tatsuhiro-t commented on CMakeLists.txt
> +  if (CMAKE_C_COMPILER_ARCHITECTURE_ID MATCHES "x64")
Remove extra white space between "if" and "(" for consistency.

2024-07-22 07:54 UTC, tatsuhiro-t commented on CMakeLists.txt
> +  if (CMAKE_CXX_COMPILER_ARCHITECTURE_ID MATCHES "x64")
ditto

2024-07-24 08:19 UTC, tatsuhiro-t commented
LGTM.  Thank you.  Could you squash commits into one?

2024-07-24 13:23 UTC, tatsuhiro-t approved these changes

2024-07-24 13:24 UTC, merged

2024-07-24 13:24 UTC, tatsuhiro-t commented
Thank you for PR. Merged now.